### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by rfay** [bhanu951/ddev-localhostrun#2]
* Please update the README, it has lots of stuff from the template. Make sure you show yourself as the maintainer.
* Looks like tests aren't working yet, that's super important.

Maybe these things are in the PR?

When this has matured just a bit more, you will want to add the `ddev-get` label so it's discoverable. 

Also, don't know if you're doing it already, but you'll probably want to check the required DDEV version. One example of doing that is at https://github.com/ddev/ddev-platformsh/blob/28b127817ed9bdfa2175c30f915b6a236e6c5a4c/install.yaml#L20-L23 but unfortunately there isn't a capability for this new bugfix.

**Comment by bhanu951** [comment]
> Please update the README, it has lots of stuff from the template. Make sure you show yourself as the maintainer.

I have already updated. Can you please have a look again?

> Looks like tests aren't working yet, that's super important.

I am not able to read the terminal output to get the generated domain name(https://github.com/bhanu951/ddev-localhostrun/pull/1/files#diff-a2bb1b04da80b87de17520a6aac3664b1cafdec2b6431697f15968522708a47cR27). Any guidance will be helpful.

> Also, don't know if you're doing it already, but you'll probably want to check the required DDEV version.

I am not checking it. Will add this.

**Comment by rfay** [comment]
> I am not able to read the terminal output to get the generated domain name(https://github.com/bhanu951/ddev-localhostrun/pull/1/files#diff-a2bb1b04da80b87de17520a6aac3664b1cafdec2b6431697f15968522708a47cR27). Any guidance will be helpful.

For ngrok/ddev share tests we use the json log output from the ngrok client. Maybe localhostrun has the same feature?

Good job, good progress!
